export const programData = {
  program: {
    id: 58598,
    name: 'Programa de Força - Joana',
    user_id: 6078,
    clone: 'original',
    clone_from: 0,
    subtitle: null,
    points: 50,
    category: 1,
    difficulty_level: 'Avançado',
    gender: 'ambos',
    location: 'qualquer',
    focus: 'completo',
    cover_path: 'https://supertreinosapp.com/img/free/FORCA.jpg',
    video_url: 'https://player.vimeo.com/video/',
    video_url_thumb: 'https://supertreinosapp.com/img/AGENDA-BANNER-PADRAO.jpg',
    description:
      'Este é um programa de nível intemediario para o desenvolvimento de força nos principais grupamentos musculares',
    weeks: '4',
    days_per_week: '3',
    minutes_per_day: '60',
    sort: 2,
    translations: null,
    created_at: '2023-06-09 09:57:48',
    updated_at: '2023-06-09 13:36:35',
    pay: '0',
    published: 1,
    premium: 0,
    home: 0,
    featured: 0,
    featured_banner: '',
    cover_url: 'https://supertreinosapp.com/img/free/FORCA.jpg',
    goals: [
      {
        id: 22,
        name: 'Ganho de Força',
        parent_id: null,
        sort: 0,
        translations:
          '{"strings_en":{"name":"Strength Gain"},"strings_es":{"name":"Ganancia de Fuerza"},"id":22}',
        created_at: null,
        updated_at: '2021-09-15 11:37:10',
        pivot: {
          program_id: 58598,
          goal_id: 22,
        },
      },
    ],
    trainings: [
      {
        id: 638964,
        cloned_from: 0,
        name: 'Dia 1',
        subtitle: 'Peitorais e bicepes',
        points: 2,
        cover_path: '1',
        video_url: null,
        description:
          'Antes de iniciar este treino, realize 10 minutos de aquecimento na bicicleta ou em qualquer aparelho de cardio',
        week_cycle: 0,
        weeks: '1',
        days_per_week: '1',
        minutes_per_day: '60',
        program_id: 58598,
        sort: 2,
        translations: null,
        groups_muscle_ids: null,
        published_at: null,
        created_at: '2023-06-09 10:02:15',
        updated_at: '2023-06-09 10:18:35',
        pay: '0',
        published: 1,
        premium: 0,
        cover_url: 'https://supertreinosapp.com/img/TREINO-BANNER-PADRAO.jpg',
      },
      {
        id: 638965,
        cloned_from: 0,
        name: 'Dia 2',
        subtitle: 'Pernas',
        points: 2,
        cover_path: '1',
        video_url: null,
        description: null,
        week_cycle: 0,
        weeks: '1',
        days_per_week: '1',
        minutes_per_day: '60',
        program_id: 58598,
        sort: 1,
        translations: null,
        groups_muscle_ids: null,
        published_at: null,
        created_at: '2023-06-09 10:13:51',
        updated_at: '2023-06-09 10:18:35',
        pay: '0',
        published: 1,
        premium: 0,
        cover_url: 'https://supertreinosapp.com/img/TREINO-BANNER-PADRAO.jpg',
      },
    ],
    frequencies: [],
    category_details: {
      id: 1,
      name: 'Séries na academia',
      old_id: 1,
      translations:
        '{"strings_en":{"name":"Gym programs"},"strings_es":{"name":"Serie en el gimnasio"},"id":1}',
      created_at: null,
      updated_at: '2021-09-15 11:37:53',
    },
  },
};

export const programsData = {
  programs: [
    {
      id: 58868,
      name: 'Programa Inicial - João',
      user_id: 6078,
      clone: 'original',
      clone_from: 0,
      subtitle: null,
      points: 50,
      category: 1,
      difficulty_level: 'Iniciante',
      gender: 'ambos',
      location: 'qualquer',
      focus: 'completo',
      cover_path: 'https://supertreinosapp.com/img/free/BASICO.jpg',
      video_url: 'https://player.vimeo.com/video/',
      video_url_thumb: 'https://supertreinosapp.com/img/AGENDA-BANNER-PADRAO.jpg',
      description: 'Programa iniciante',
      weeks: '4',
      days_per_week: '2',
      minutes_per_day: '40',
      sort: 2,
      translations: null,
      created_at: '2023-06-12 11:52:30',
      updated_at: '2023-06-12 11:52:30',
      pay: '0',
      published: 1,
      premium: 0,
      home: 0,
      featured: 0,
      featured_banner: '',
      cover_url: 'https://supertreinosapp.com/img/free/BASICO.jpg',
      liked_by_customer: null,
      looked_by_customer: null,
      category_details: {
        id: 1,
        name: 'Séries na academia',
        old_id: 1,
        translations:
          '{"strings_en":{"name":"Gym programs"},"strings_es":{"name":"Serie en el gimnasio"},"id":1}',
        created_at: null,
        updated_at: '2021-09-15 11:37:53',
      },
      goals: [
        {
          id: 1,
          name: 'Definição | Emagrecimento',
          parent_id: null,
          sort: 0,
          translations:
            '{"strings_en":{"name":"Fatloss"},"strings_es":{"name":"Definición muscular"},"id":1}',
          created_at: '2018-03-19 19:43:39',
          updated_at: '2022-03-25 17:25:09',
          pivot: {
            program_id: 58868,
            goal_id: 1,
          },
        },
      ],
      students: [],
    },
    {
      id: 58869,
      name: 'Programa de Força - Joana',
      user_id: 6078,
      clone: 'original',
      clone_from: 0,
      subtitle: null,
      points: 50,
      category: 1,
      difficulty_level: 'Avançado',
      gender: 'ambos',
      location: 'qualquer',
      focus: 'completo',
      cover_path: 'https://supertreinosapp.com/img/free/FORCA.jpg',
      video_url: 'https://player.vimeo.com/video/',
      video_url_thumb: 'https://supertreinosapp.com/img/AGENDA-BANNER-PADRAO.jpg',
      description:
        'Este é um programa de nível intemediario para o desenvolvimento de força nos principais grupamentos musculares',
      weeks: '4',
      days_per_week: '3',
      minutes_per_day: '60',
      sort: 1,
      translations: null,
      created_at: '2023-06-09 09:57:48',
      updated_at: '2023-06-12 11:52:30',
      pay: '0',
      published: 1,
      premium: 0,
      home: 0,
      featured: 0,
      featured_banner: '',
      cover_url: 'https://supertreinosapp.com/img/free/FORCA.jpg',
      liked_by_customer: null,
      looked_by_customer: null,
      category_details: {
        id: 1,
        name: 'Séries na academia',
        old_id: 1,
        translations:
          '{"strings_en":{"name":"Gym programs"},"strings_es":{"name":"Serie en el gimnasio"},"id":1}',
        created_at: null,
        updated_at: '2021-09-15 11:37:53',
      },
      goals: [
        {
          id: 22,
          name: 'Ganho de Força',
          parent_id: null,
          sort: 0,
          translations:
            '{"strings_en":{"name":"Strength Gain"},"strings_es":{"name":"Ganancia de Fuerza"},"id":22}',
          created_at: null,
          updated_at: '2021-09-15 11:37:10',
          pivot: {
            program_id: 58598,
            goal_id: 22,
          },
        },
      ],
      students: [
        {
          id: 135734,
          customer_id: 441120,
          user_id: 6078,
          program_id: 58598,
          created_at: '2023-06-09 10:20:58',
          updated_at: '2023-06-09 10:20:58',
        },
      ],
    },
    {
      id: 58870,
      name: 'Programa Inicial - Maria',
      user_id: 6078,
      clone: 'original',
      clone_from: 0,
      subtitle: null,
      points: 50,
      category: 1,
      difficulty_level: 'Intermediário',
      gender: 'ambos',
      location: 'qualquer',
      focus: 'completo',
      cover_path: 'https://supertreinosapp.com/img/free/BASICO.jpg',
      video_url: 'https://player.vimeo.com/video/',
      video_url_thumb: 'https://supertreinosapp.com/img/AGENDA-BANNER-PADRAO.jpg',
      description: 'Programa iniciante',
      weeks: null,
      days_per_week: '2',
      minutes_per_day: '40',
      sort: 2,
      translations: null,
      created_at: '2023-06-12 11:52:30',
      updated_at: '2023-06-12 11:52:30',
      pay: '0',
      published: 1,
      premium: 0,
      home: 0,
      featured: 0,
      featured_banner: '',
      cover_url: 'https://supertreinosapp.com/img/free/BASICO.jpg',
      liked_by_customer: null,
      looked_by_customer: null,
      category_details: {
        id: 1,
        name: 'Séries na academia',
        old_id: 1,
        translations:
          '{"strings_en":{"name":"Gym programs"},"strings_es":{"name":"Serie en el gimnasio"},"id":1}',
        created_at: null,
        updated_at: '2021-09-15 11:37:53',
      },
      goals: [
        {
          id: 1,
          name: 'Definição | Emagrecimento',
          parent_id: null,
          sort: 0,
          translations:
            '{"strings_en":{"name":"Fatloss"},"strings_es":{"name":"Definición muscular"},"id":1}',
          created_at: '2018-03-19 19:43:39',
          updated_at: '2022-03-25 17:25:09',
          pivot: {
            program_id: 58868,
            goal_id: 1,
          },
        },
      ],
      students: [],
    },
    {
      id: 58871,
      name: 'Programa de Força - Paulo',
      user_id: 6078,
      clone: 'original',
      clone_from: 0,
      subtitle: null,
      points: 50,
      category: 1,
      difficulty_level: 'Expert',
      gender: 'ambos',
      location: 'qualquer',
      focus: 'completo',
      cover_path: 'https://supertreinosapp.com/img/free/FORCA.jpg',
      video_url: 'https://player.vimeo.com/video/',
      video_url_thumb: 'https://supertreinosapp.com/img/AGENDA-BANNER-PADRAO.jpg',
      description:
        'Este é um programa de nível intemediario para o desenvolvimento de força nos principais grupamentos musculares',
      weeks: '4',
      days_per_week: '3',
      minutes_per_day: '60',
      sort: 1,
      translations: null,
      created_at: '2023-06-09 09:57:48',
      updated_at: '2023-06-12 11:52:30',
      pay: '0',
      published: 1,
      premium: 0,
      home: 0,
      featured: 0,
      featured_banner: '',
      cover_url: 'https://supertreinosapp.com/img/free/FORCA.jpg',
      liked_by_customer: null,
      looked_by_customer: null,
      category_details: {
        id: 1,
        name: 'Séries na academia',
        old_id: 1,
        translations:
          '{"strings_en":{"name":"Gym programs"},"strings_es":{"name":"Serie en el gimnasio"},"id":1}',
        created_at: null,
        updated_at: '2021-09-15 11:37:53',
      },
      goals: [
        {
          id: 22,
          name: 'Ganho de Força',
          parent_id: null,
          sort: 0,
          translations:
            '{"strings_en":{"name":"Strength Gain"},"strings_es":{"name":"Ganancia de Fuerza"},"id":22}',
          created_at: null,
          updated_at: '2021-09-15 11:37:10',
          pivot: {
            program_id: 58598,
            goal_id: 22,
          },
        },
      ],
      students: [
        {
          id: 135734,
          customer_id: 441120,
          user_id: 6078,
          program_id: 58598,
          created_at: '2023-06-09 10:20:58',
          updated_at: '2023-06-09 10:20:58',
        },
      ],
    },
    {
      id: 58872,
      name: 'Programa Inicial - João',
      user_id: 6078,
      clone: 'original',
      clone_from: 0,
      subtitle: null,
      points: 50,
      category: 1,
      difficulty_level: 'Iniciante',
      gender: 'ambos',
      location: 'qualquer',
      focus: 'completo',
      cover_path: 'https://supertreinosapp.com/img/free/BASICO.jpg',
      video_url: 'https://player.vimeo.com/video/',
      video_url_thumb: 'https://supertreinosapp.com/img/AGENDA-BANNER-PADRAO.jpg',
      description: 'Programa iniciante',
      weeks: '4',
      days_per_week: '2',
      minutes_per_day: '40',
      sort: 2,
      translations: null,
      created_at: '2023-06-12 11:52:30',
      updated_at: '2023-06-12 11:52:30',
      pay: '0',
      published: 1,
      premium: 0,
      home: 0,
      featured: 0,
      featured_banner: '',
      cover_url: 'https://supertreinosapp.com/img/free/BASICO.jpg',
      liked_by_customer: null,
      looked_by_customer: null,
      category_details: {
        id: 1,
        name: 'Séries na academia',
        old_id: 1,
        translations:
          '{"strings_en":{"name":"Gym programs"},"strings_es":{"name":"Serie en el gimnasio"},"id":1}',
        created_at: null,
        updated_at: '2021-09-15 11:37:53',
      },
      goals: [
        {
          id: 1,
          name: 'Definição | Emagrecimento',
          parent_id: null,
          sort: 0,
          translations:
            '{"strings_en":{"name":"Fatloss"},"strings_es":{"name":"Definición muscular"},"id":1}',
          created_at: '2018-03-19 19:43:39',
          updated_at: '2022-03-25 17:25:09',
          pivot: {
            program_id: 58868,
            goal_id: 1,
          },
        },
      ],
      students: [],
    },
    {
      id: 58873,
      name: 'Programa de Força - Joana',
      user_id: 6078,
      clone: 'original',
      clone_from: 0,
      subtitle: null,
      points: 50,
      category: 1,
      difficulty_level: 'Avançado',
      gender: 'ambos',
      location: 'qualquer',
      focus: 'completo',
      cover_path: 'https://supertreinosapp.com/img/free/FORCA.jpg',
      video_url: 'https://player.vimeo.com/video/',
      video_url_thumb: 'https://supertreinosapp.com/img/AGENDA-BANNER-PADRAO.jpg',
      description:
        'Este é um programa de nível intemediario para o desenvolvimento de força nos principais grupamentos musculares',
      weeks: '4',
      days_per_week: '3',
      minutes_per_day: '60',
      sort: 1,
      translations: null,
      created_at: '2023-06-09 09:57:48',
      updated_at: '2023-06-12 11:52:30',
      pay: '0',
      published: 1,
      premium: 0,
      home: 0,
      featured: 0,
      featured_banner: '',
      cover_url: 'https://supertreinosapp.com/img/free/FORCA.jpg',
      liked_by_customer: null,
      looked_by_customer: null,
      category_details: {
        id: 1,
        name: 'Séries na academia',
        old_id: 1,
        translations:
          '{"strings_en":{"name":"Gym programs"},"strings_es":{"name":"Serie en el gimnasio"},"id":1}',
        created_at: null,
        updated_at: '2021-09-15 11:37:53',
      },
      goals: [
        {
          id: 22,
          name: 'Ganho de Força',
          parent_id: null,
          sort: 0,
          translations:
            '{"strings_en":{"name":"Strength Gain"},"strings_es":{"name":"Ganancia de Fuerza"},"id":22}',
          created_at: null,
          updated_at: '2021-09-15 11:37:10',
          pivot: {
            program_id: 58598,
            goal_id: 22,
          },
        },
      ],
      students: [
        {
          id: 135734,
          customer_id: 441120,
          user_id: 6078,
          program_id: 58598,
          created_at: '2023-06-09 10:20:58',
          updated_at: '2023-06-09 10:20:58',
        },
      ],
    },
  ],
};
