export const trainingsData = {
  trainings: [
    {
      id: 642611,
      cloned_from: 0,
      name: 'Treino de força',
      subtitle: 'Dia 1',
      points: 2,
      cover_path: '1',
      video_url: null,
      description: 'Treino de força',
      week_cycle: 0,
      weeks: '4',
      days_per_week: '1',
      minutes_per_day: '60',
      program_id: 58878,
      sort: 3,
      translations: null,
      groups_muscle_ids: null,
      published_at: null,
      created_at: '2023-06-13 18:54:41',
      updated_at: '2023-06-14 11:04:13',
      pay: '0',
      published: 1,
      premium: 0,
      likes_count: 0,
      cover_url: 'https://supertreinosapp.com/img/TREINO-BANNER-PADRAO.jpg',
      liked_by_customer: null,
      completed_by_customer: null,
      looked_by_customer: null,
      workouts: [],
    },
    {
      id: 642622,
      cloned_from: 0,
      name: 'Treino 2',
      subtitle: null,
      points: 2,
      cover_path: '0',
      video_url: null,
      description: null,
      week_cycle: 0,
      weeks: null,
      days_per_week: null,
      minutes_per_day: null,
      program_id: 58878,
      sort: 2,
      translations: null,
      groups_muscle_ids: null,
      published_at: null,
      created_at: '2023-06-13 19:04:01',
      updated_at: '2023-06-14 11:04:13',
      pay: '0',
      published: 0,
      premium: 0,
      likes_count: 0,
      cover_url: 'https://supertreinosapp.com/0',
      liked_by_customer: null,
      completed_by_customer: null,
      looked_by_customer: null,
      workouts: [],
    },
    {
      id: 642876,
      cloned_from: 0,
      name: 'Treino dia 3',
      subtitle: 'Treino de membros superiores',
      points: 2,
      cover_path: '1',
      video_url: null,
      description: 'Treino para os membros superiores',
      week_cycle: 0,
      weeks: '4',
      days_per_week: '1',
      minutes_per_day: '60',
      program_id: 58878,
      sort: 1,
      translations: null,
      groups_muscle_ids: null,
      published_at: null,
      created_at: '2023-06-14 11:04:11',
      updated_at: '2023-06-14 11:04:13',
      pay: '0',
      published: 1,
      premium: 0,
      likes_count: 0,
      cover_url: 'https://supertreinosapp.com/img/TREINO-BANNER-PADRAO.jpg',
      liked_by_customer: null,
      completed_by_customer: null,
      looked_by_customer: null,
      workouts: [],
    },
  ],
};

export const trainingData = {
  training: {
    id: 642876,
    cloned_from: 0,
    name: 'Treino dia 3',
    subtitle: 'Treino de membros superiores',
    points: 2,
    cover_path: '1',
    video_url: null,
    description: 'Treino para os membros superiores',
    week_cycle: 0,
    weeks: '4',
    days_per_week: '1',
    minutes_per_day: '60',
    program_id: 58878,
    sort: 3,
    translations: null,
    groups_muscle_ids: null,
    published_at: null,
    created_at: '2023-06-14 11:04:11',
    updated_at: '2023-06-15 17:05:23',
    pay: '0',
    published: 1,
    premium: 0,
    likes_count: 0,
    goal: 2,
    cover_url: 'https://supertreinosapp.com/img/TREINO-BANNER-PADRAO.jpg',
    liked_by_customer: null,
    completed_by_customer: null,
    looked_by_customer: null,
    goals: [
      {
        id: 2,
        name: 'Sem \u00eanfase',
        parent_id: 1,
        sort: 0,
        translations: null,
        created_at: '2018-03-19 19:43:39',
        updated_at: '2018-03-19 19:43:39',
        pivot: { training_id: 642876, goal_id: 2 },
      },
    ],
    workouts: [],
  },
};

//{"id":0,"cloned_from":0,"name":"Teste Bloqueado","subtitle":"Bloqueado","points":2,"video_url":"","description":"","week_cycle":0,"weeks":"","days_per_week":"","minutes_per_day":"","program_id":58878,"sort":0,"translations":"","groups_muscle_ids":"","published_at":"","created_at":"","updated_at":"","pay":false,"published":1,"premium":false,"likes_count":0,"goal":0,"cover_url":"https://supertreinosapp.com/img/TREINO-BANNER-PADRAO.jpg","liked_by_customer":"","completed_by_customer":"","looked_by_customer":"","goals":"","workouts":"","cover_path":true}
