export const workoutsData = {
  training_id: '642876',
  workouts: [
    {
      id: 5485622,
      name: 'Exercício Teste',
      series_repetitions: '3x15',
      intervals: 60,
      weight_suggestion: '20kg',
      video_url: 'https://player.vimeo.com/video/',
      cover_path: '/img/EXERCICIO-BANNER-PADRAO.jpg',
      description: 'Executar Exercício Biset',
      training_id: 642876,
      serie_id: 0,
      library_workout_id: 0,
      sort: 106501,
      translations: null,
      created_at: '2023-06-16 11:59:51',
      updated_at: '2023-06-16 11:59:51',
      cover_url: 'https://supertreinosapp.com/img/EXERCICIO-BANNER-PADRAO.jpg',
      serie_check: false,
      library: null,
    },
    {
      id: 5485676,
      name: 'Abdominais Heel Touches',
      series_repetitions: null,
      intervals: 0,
      weight_suggestion: null,
      video_url: 'https://player.vimeo.com/video/268432949',
      cover_path: 'storage/cover/workout/5485676/5485676_cover_1686919043.jpeg',
      description:
        'Deitado sobre um colchonete, mantenha os braços estendidos ao lado do corpo. Flexione a coluna tentando encostar as mãos nos calcanhares alternando os lados. Inspire na posição inicial e expire (solte o ar) na subida.',
      training_id: 642876,
      serie_id: 0,
      library_workout_id: 59,
      sort: 0,
      translations:
        '{"strings_en":{"name":"Sit-ups Heel Touches","description":"Lying on a mat, keep your arms out at your sides. Flex your spine trying to rest your hands on your heels by alternating sides. Inhale in the starting position and exhale (exhale) on the way up."},"strings_es":{"name":"Abdominales Toques de tal\\u00f3n","description":"Acostado sobre una colchoneta, mantenga los brazos extendidos a los lados. Flexione la columna tratando de apoyar las manos en los talones alternando los lados. Inhala en la posici\\u00f3n inicial y exhala (exhala) en el camino hacia arriba."}}',
      created_at: '2023-06-16 12:37:23',
      updated_at: '2023-06-16 12:37:23',
      cover_url:
        'https://supertreinosapp.com/storage/cover/workout/5485676/5485676_cover_1686919043.jpeg',
      serie_check: false,
      library: {
        id: 59,
        user_id: 1,
        premium: 0,
        published: 1,
        name: 'Abdominais Heel Touches',
        gender: 'masc',
        workout_type_ids: [3],
        workout_muscle_ids: [11],
        workout_equip_ids: [6],
        workout_method_ids: [1],
        series_repetitions: null,
        intervals: 0,
        video_url: 'https://player.vimeo.com/video/268432949',
        cover_path: 'storage/cover/library/59/59_cover_1575224427.jpeg',
        description:
          'Deitado sobre um colchonete, mantenha os braços estendidos ao lado do corpo. Flexione a coluna tentando encostar as mãos nos calcanhares alternando os lados. Inspire na posição inicial e expire (solte o ar) na subida.',
        sort: 47,
        translations:
          '{"strings_en":{"name":"Sit-ups Heel Touches","description":"Lying on a mat, keep your arms out at your sides. Flex your spine trying to rest your hands on your heels by alternating sides. Inhale in the starting position and exhale (exhale) on the way up."},"strings_es":{"name":"Abdominales Toques de tal\\u00f3n","description":"Acostado sobre una colchoneta, mantenga los brazos extendidos a los lados. Flexione la columna tratando de apoyar las manos en los talones alternando los lados. Inhala en la posici\\u00f3n inicial y exhala (exhala) en el camino hacia arriba."}}',
        created_at: '2019-12-01 18:20:27',
        updated_at: '2023-06-16 11:11:01',
        cover_url: 'https://supertreinosapp.com/storage/cover/library/59/59_cover_1575224427.jpeg',
        search_string: 'Abdominais Heel Touches|[pr0|[pu1',
      },
    },
  ],
  total_workouts_not_merged: 2,
};
